name: "Build iOS app"

on:
  workflow_dispatch:
    inputs:
      release_name:
        description: 'Enter the name of the release'
        required: true

permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version
      - uses: pnpm/action-setup@v4
        with:
          version: 9.9.0
      - name: checkout repository
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
      - uses: actions/setup-go@v5
        with:
          go-version-file: 'alist/go.mod'

      - name: build alist-web
        run: cd alist-web && pnpm i && pnpm run build && mv ./dist ../alist/public/

      - name: build alist
        run: |
          cd alist && \
          go install golang.org/x/mobile/cmd/gomobile@latest && \
          gomobile init && \
          gomobile bind -target ios -bundleid com.gendago.alist -o ../ios/alist/Alistlib.xcframework -ldflags "-s -w" github.com/alist-org/alist/v3/alistlib

      - name: modify Podfile
        run: sed -i '' 's/alist/alist-without-icloud/g' ios/Podfile

      - name: install dependencies
        run: yarn && npx pod-install

      - name: build archive
        run: |
          xcodebuild -workspace ./ios/alist.xcworkspace \
          -scheme alist-without-icloud \
          -configuration Release clean archive \
          -archivePath unsigned.xcarchive \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO

      - name: export ipa
        env:
          EXPORT_OPTIONS_PLIST: ${{ secrets.EXPORT_OPTIONS_PLIST }}
        run: |
          cp -r ./unsigned.xcarchive/Products/Applications ./Payload && \
          zip -r AListServer.ipa ./Payload/

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ github.event.inputs.release_name }}
          prerelease: false
          files: AListServer.ipa
